import path from 'node:path'
import { getSpriteShapeId } from '../../shape-id.js'
import { generateReactAssetUrlCode } from '../../targets/index.js'
import type { SpriteAssetTarget } from '../../targets/types.js'
import type { SpriteFormat } from '../../types.js'
import { generateSpriteManifest } from './manifest.js'
import { toPascalCase } from './naming.js'
import type { ResolvedReactSpriteConfig } from './types.js'

const GENERATED_MARKER = '@generated by @gromlab/svg-sprites. Do not edit.'
const GENERATED_NOTICE = [
  '----------------------------------------------------------------------',
  '## АВТОМАТИЧЕСКИ СГЕНЕРИРОВАННЫЙ ФАЙЛ                               ##',
  '##                                                                  ##',
  '## Не редактируйте вручную: изменения будут перезаписаны.           ##',
  '## Для изменений перегенерируйте SVG-спрайт.                        ##',
  '##                                                                  ##',
  '## Генератор: @gromlab/svg-sprites                                  ##',
  '## Репозиторий: https://gromlab.ru/gromov/svg-sprites               ##',
  '----------------------------------------------------------------------',
]

type ReactCodegenOptions = {
  config: ResolvedReactSpriteConfig
  format: SpriteFormat
  iconNames: string[]
  sprite: Uint8Array
  target: SpriteAssetTarget
}

export type GeneratedFile = {
  path: string
  content: string | Uint8Array
}

function toCamelCase(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase())
}

function generateBlockHeader(generatedNotice: boolean): string {
  if (!generatedNotice) return `/* ${GENERATED_MARKER} */`

  return [
    '/*',
    ...GENERATED_NOTICE.map((line) => ` * ${line}`),
    ' */',
  ].join('\n')
}

function generateSvgHeader(generatedNotice: boolean): string {
  if (!generatedNotice) return `<!-- ${GENERATED_MARKER} -->`

  return [
    '<!--',
    ...GENERATED_NOTICE.slice(1, -1).map((line) => `  ${line}`),
    '-->',
  ].join('\n')
}

function generateGitignore(): string {
  return `# ${GENERATED_MARKER}\n/generated/\n/index.ts\n/manifest.ts\n`
}

function formatSvg(content: string): string {
  let depth = 0
  const lines = content.replace(/></g, '>\n<').split('\n')

  const formatted = lines.map((line) => {
    const trimmed = line.trim()
    const tags = trimmed.match(/<[^>]+>/g) ?? []
    const startsWithClosingTag = trimmed.startsWith('</')

    if (startsWithClosingTag) depth = Math.max(0, depth - 1)

    const formattedLine = `${'  '.repeat(depth)}${trimmed}`

    for (const tag of tags) {
      if (tag.startsWith('</')) {
        if (!startsWithClosingTag) depth = Math.max(0, depth - 1)
      } else if (!tag.startsWith('<?') && !tag.startsWith('<!') && !tag.endsWith('/>')) {
        depth += 1
      }
    }

    return formattedLine
  })

  return `${formatted.join('\n')}\n`
}

function markSvg(content: Uint8Array, generatedNotice: boolean): string {
  const svg = formatSvg(new TextDecoder().decode(content))
  const header = generateSvgHeader(generatedNotice)
  return svg.startsWith('<?xml')
    ? svg.replace(/^(<\?xml[^?]*\?>)\s*/, `$1\n${header}\n`)
    : `${header}\n${svg}`
}

function generateDescriptionComment(name: string, description?: string): string[] {
  const text = description ?? `Имена иконок SVG-спрайта «${name}».`
  return [
    '/**',
    ...text.split(/\r?\n/).map((line) => ` * ${line.replace(/\*\//g, '* /')}`),
    ' */',
  ]
}

function generateTypes(
  name: string,
  description: string | undefined,
  iconNames: string[],
  generatedNotice: boolean,
): string {
  const pascalName = toPascalCase(name)
  const camelName = toCamelCase(name)
  const iconNamesVariable = `${camelName}IconNames`

  return [
    generateBlockHeader(generatedNotice),
    '',
    ...generateDescriptionComment(name, description),
    `export const ${iconNamesVariable} = [`,
    ...iconNames.map((iconName) => `  ${JSON.stringify(iconName)},`),
    '] as const',
    '',
    `export type ${pascalName}IconName = typeof ${iconNamesVariable}[number]`,
    '',
  ].join('\n')
}

function generateComponent(
  name: string,
  generatedNotice: boolean,
  target: SpriteAssetTarget,
  iconNames: string[],
): string {
  const pascalName = toPascalCase(name)
  const assetUrlCode = generateReactAssetUrlCode(target, 'sprite.svg')

  return [
    generateBlockHeader(generatedNotice),
    "import type { CSSProperties, HTMLAttributes, SVGAttributes } from 'react'",
    "import styles from './styles.module.css'",
    `import type { ${pascalName}IconName } from './types'`,
    ...assetUrlCode.imports,
    '',
    ...assetUrlCode.declarations,
    ...(assetUrlCode.declarations.length > 0 ? [''] : []),
    `const iconIds: Record<${pascalName}IconName, string> = {`,
    ...iconNames.map((iconName) => `  ${JSON.stringify(iconName)}: ${JSON.stringify(getSpriteShapeId(iconName))},`),
    '}',
    '',
    `export type ${pascalName}IconStyle = CSSProperties & Partial<Record<\`--icon-color-\${number}\`, string | number>>`,
    '',
    `type ${pascalName}IconBaseProps = {`,
    `  icon: ${pascalName}IconName`,
    '}',
    '',
    `type ${pascalName}IconSvgProps = ${pascalName}IconBaseProps & {`,
    '  wrapped?: false',
    `} & Omit<SVGAttributes<SVGSVGElement>, 'style'> & {`,
    `  style?: ${pascalName}IconStyle`,
    '}',
    '',
    `type ${pascalName}IconWrappedProps = ${pascalName}IconBaseProps & {`,
    '  wrapped: true',
    `} & Omit<HTMLAttributes<HTMLSpanElement>, 'style'> & {`,
    `  style?: ${pascalName}IconStyle`,
    '}',
    '',
    `export type ${pascalName}IconProps =`,
    `  | ${pascalName}IconSvgProps`,
    `  | ${pascalName}IconWrappedProps`,
    '',
    `/** Иконка из SVG-спрайта «${name}». */`,
    `export const ${pascalName}Icon = (props: ${pascalName}IconProps) => {`,
    '  const { icon, wrapped, className, ...rest } = props',
    `  const href = ${assetUrlCode.variableName} + '#' + iconIds[icon]`,
    '',
    '  if (wrapped) {',
    '    const htmlAttributes = rest as HTMLAttributes<HTMLSpanElement>',
    '    return (',
    "      <span {...htmlAttributes} className={[styles.wrap, className].filter(Boolean).join(' ')}>",
    '        <svg>',
    '          <use href={href} />',
    '        </svg>',
    '      </span>',
    '    )',
    '  }',
    '',
    '  const svgAttributes = rest as SVGAttributes<SVGSVGElement>',
    '  return (',
    "    <svg {...svgAttributes} className={[styles.root, className].filter(Boolean).join(' ')}>",
    '      <use href={href} />',
    '    </svg>',
    '  )',
    '}',
    '',
  ].join('\n')
}

function generateCss(generatedNotice: boolean, addTransition: boolean): string {
  const transitionRules = addTransition
    ? [
        '  transition-property: fill, stroke, color;',
        '  transition-duration: 0.3s;',
        '  transition-timing-function: ease;',
      ]
    : []

  return [
    generateBlockHeader(generatedNotice),
    '',
    '.root {',
    ...transitionRules,
    '}',
    '',
    '.wrap {',
    '  display: inline-flex;',
    '}',
    '',
    '.wrap svg {',
    '  width: 100%;',
    '  height: 100%;',
    ...transitionRules,
    '}',
    '',
  ].join('\n')
}

function generateRootIndex(name: string, generatedNotice: boolean): string {
  const pascalName = toPascalCase(name)
  const iconNamesVariable = `${toCamelCase(name)}IconNames`

  return [
    generateBlockHeader(generatedNotice),
    `export { ${pascalName}Icon } from './generated/react-component'`,
    `export type { ${pascalName}IconProps, ${pascalName}IconStyle } from './generated/react-component'`,
    `export { ${iconNamesVariable} } from './generated/types'`,
    `export type { ${pascalName}IconName } from './generated/types'`,
    '',
  ].join('\n')
}

/** Создаёт все управляемые файлы React sprite-модуля в памяти. */
export function generateReactFiles(options: ReactCodegenOptions): GeneratedFile[] {
  const { config, format, iconNames, sprite, target } = options
  const { name, description, generatedNotice } = config

  return [
    {
      path: '.gitignore',
      content: generateGitignore(),
    },
    {
      path: path.posix.join('generated', 'sprite.svg'),
      content: markSvg(sprite, generatedNotice),
    },
    {
      path: path.posix.join('generated', 'types.ts'),
      content: generateTypes(name, description, iconNames, generatedNotice),
    },
    {
      path: path.posix.join('generated', 'react-component.tsx'),
      content: generateComponent(name, generatedNotice, target, iconNames),
    },
    {
      path: path.posix.join('generated', 'styles.module.css'),
      content: generateCss(generatedNotice, config.transform.addTransition ?? true),
    },
    {
      path: 'manifest.ts',
      content: generateSpriteManifest({
        header: generateBlockHeader(generatedNotice),
        name,
        description,
        format,
        iconNames,
        sprite,
        target,
      }),
    },
    {
      path: 'index.ts',
      content: generateRootIndex(name, generatedNotice),
    },
  ]
}
