import { randomUUID } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import type { GeneratedFile } from './codegen.js'

const MANIFEST_FILE = '.svg-sprites.manifest.json'
const GENERATOR = '@gromlab/svg-sprites'
const GENERATED_MARKER = '@generated by @gromlab/svg-sprites'
const GENERATED_NOTICE_MARKER = 'АВТОМАТИЧЕСКИ СГЕНЕРИРОВАННЫЙ ФАЙЛ'
const ROOT_MANAGED_FILES = new Set(['.gitignore', 'index.ts', 'manifest.ts'])

type Manifest = {
  version: 1
  generator: typeof GENERATOR
  files: string[]
  warning?: string
}

function normalizeManagedPath(relativePath: string): string {
  const normalized = relativePath.replaceAll('\\', '/')
  const parts = normalized.split('/')
  const isRootFile = ROOT_MANAGED_FILES.has(normalized)
  const isGeneratedFile = parts.length === 2
    && parts[0] === 'generated'
    && parts[1] !== ''
    && parts[1] !== '.'
    && parts[1] !== '..'

  if (!isRootFile && !isGeneratedFile) {
    throw new Error(`Invalid generated file path: ${relativePath}`)
  }

  return normalized
}

function resolveManagedPath(rootDir: string, relativePath: string): string {
  const normalized = normalizeManagedPath(relativePath)
  const resolved = path.resolve(rootDir, normalized)
  const relative = path.relative(rootDir, resolved)

  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error(`Invalid generated file path: ${relativePath}`)
  }

  return resolved
}

function assertNoSymlinks(rootDir: string, filePath: string): void {
  const relative = path.relative(rootDir, filePath)
  let currentPath = rootDir

  for (const segment of relative.split(path.sep)) {
    currentPath = path.join(currentPath, segment)
    try {
      if (fs.lstatSync(currentPath).isSymbolicLink()) {
        throw new Error(`Symbolic links are not allowed in generated paths: ${currentPath}`)
      }
    } catch (error) {
      if (error instanceof Error && 'code' in error && error.code === 'ENOENT') continue
      throw error
    }
  }
}

function readManifest(rootDir: string, manifestPath: string): Manifest | null {
  assertNoSymlinks(rootDir, manifestPath)
  if (!fs.existsSync(manifestPath)) return null

  let manifest: unknown
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
  } catch {
    throw new Error(`Cannot parse generated files manifest: ${manifestPath}`)
  }

  if (
    !manifest
    || typeof manifest !== 'object'
    || !('version' in manifest)
    || manifest.version !== 1
    || !('generator' in manifest)
    || manifest.generator !== GENERATOR
    || !('files' in manifest)
    || !Array.isArray(manifest.files)
    || !manifest.files.every((file) => typeof file === 'string')
  ) {
    throw new Error(`Invalid generated files manifest: ${manifestPath}`)
  }

  return {
    ...(manifest as Manifest),
    files: (manifest as Manifest).files.map(normalizeManagedPath),
  }
}

function hasGeneratedMarker(filePath: string): boolean {
  if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) return false
  const content = fs.readFileSync(filePath, 'utf-8')
  return content.includes(GENERATED_MARKER) || content.includes(GENERATED_NOTICE_MARKER)
}

function writeFileAtomic(rootDir: string, filePath: string, content: string | Uint8Array): void {
  assertNoSymlinks(rootDir, filePath)
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  assertNoSymlinks(rootDir, filePath)

  const temporaryPath = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.${process.pid}.${randomUUID()}.tmp`,
  )

  try {
    fs.writeFileSync(temporaryPath, content, { flag: 'wx' })
    fs.renameSync(temporaryPath, filePath)
  } finally {
    if (fs.existsSync(temporaryPath)) fs.unlinkSync(temporaryPath)
  }
}

/** Обновляет только файлы, которыми владеет React-генератор. */
export function writeReactFiles(
  rootDir: string,
  files: GeneratedFile[],
  generatedNotice: boolean,
): void {
  const generatedDir = path.join(rootDir, 'generated')
  const manifestPath = path.join(generatedDir, MANIFEST_FILE)
  const previousManifest = readManifest(rootDir, manifestPath)
  const previousFiles = new Set(previousManifest?.files ?? [])
  const nextFiles = files.map((file) => normalizeManagedPath(file.path))
  const obsoleteFiles: string[] = []

  for (const file of files) {
    const filePath = resolveManagedPath(rootDir, file.path)
    assertNoSymlinks(rootDir, filePath)
    if (fs.existsSync(filePath) && !hasGeneratedMarker(filePath)) {
      throw new Error(
        `Refusing to overwrite a user file: ${filePath}\n` +
        'Move the file or choose another sprite directory.',
      )
    }
  }

  for (const relativePath of previousFiles) {
    if (nextFiles.includes(relativePath)) continue
    const filePath = resolveManagedPath(rootDir, relativePath)
    assertNoSymlinks(rootDir, filePath)

    if (fs.existsSync(filePath)) {
      if (!hasGeneratedMarker(filePath)) {
        throw new Error(`Refusing to delete a user file: ${filePath}`)
      }
      obsoleteFiles.push(filePath)
    }
  }

  for (const filePath of obsoleteFiles) fs.unlinkSync(filePath)

  for (const file of files) {
    writeFileAtomic(rootDir, resolveManagedPath(rootDir, file.path), file.content)
  }

  const manifest: Manifest = {
    version: 1,
    generator: GENERATOR,
    files: nextFiles,
    ...(generatedNotice && {
      warning: 'АВТОМАТИЧЕСКИ СГЕНЕРИРОВАННЫЙ ФАЙЛ. Не редактируйте вручную: изменения будут перезаписаны.',
    }),
  }
  writeFileAtomic(rootDir, manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)
}
