export const apps = [
  { id: 'standalone', kind: 'static', output: 'dist', expectedSpritePath: '/app-icons/sprite.svg', expectedRemoteSpritePath: '/remote-app-icons/sprite.svg' },
  { id: 'standalone-vite', kind: 'static', output: 'dist' },
  { id: 'standalone-webpack', kind: 'static', output: 'dist' },
  { id: 'react-vite', kind: 'static', output: 'dist', frameworkTab: 'React' },
  { id: 'react-webpack', kind: 'static', output: 'dist', frameworkTab: 'React' },
  { id: 'next-app-turbopack', kind: 'next', frameworkTab: 'React' },
  { id: 'next-app-webpack', kind: 'next', frameworkTab: 'React' },
  { id: 'next-pages-turbopack', kind: 'next', frameworkTab: 'React' },
  { id: 'next-pages-webpack', kind: 'next', frameworkTab: 'React' },
  { id: 'vue-vite', kind: 'static', output: 'dist', frameworkTab: 'Vue' },
  { id: 'vue-webpack', kind: 'static', output: 'dist', frameworkTab: 'Vue' },
  { id: 'nuxt-vite', kind: 'nuxt', frameworkTab: 'Vue' },
  { id: 'nuxt-webpack', kind: 'nuxt', frameworkTab: 'Vue' },
  { id: 'svelte-vite', kind: 'static', output: 'dist', frameworkTab: 'Svelte' },
  { id: 'svelte-webpack', kind: 'static', output: 'dist', frameworkTab: 'Svelte' },
  { id: 'sveltekit', kind: 'sveltekit', frameworkTab: 'Svelte' },
  { id: 'angular', kind: 'static', output: 'dist/angular/browser', frameworkTab: 'Angular' },
  { id: 'angular-webpack', kind: 'static', output: 'dist', frameworkTab: 'Angular' },
  { id: 'astro', kind: 'static', output: 'dist', frameworkTab: 'Astro' },
  { id: 'solid-vite', kind: 'static', output: 'dist', frameworkTab: 'Solid' },
  { id: 'solid-webpack', kind: 'static', output: 'dist', frameworkTab: 'Solid' },
  { id: 'solid-start-vite', kind: 'solid-start', frameworkTab: 'SolidStart' },
  { id: 'preact-vite', kind: 'static', output: 'dist', frameworkTab: 'Preact' },
  { id: 'preact-webpack', kind: 'static', output: 'dist', frameworkTab: 'Preact' },
  { id: 'qwik-vite', kind: 'static', output: 'dist', frameworkTab: 'Qwik' },
  { id: 'lit-vite', kind: 'static', output: 'dist', frameworkTab: 'Lit', shadowIcon: true },
  { id: 'lit-webpack', kind: 'static', output: 'dist', frameworkTab: 'Lit', shadowIcon: true },
  { id: 'alpine-vite', kind: 'static', output: 'dist', frameworkTab: 'Alpine' },
  { id: 'alpine-webpack', kind: 'static', output: 'dist', frameworkTab: 'Alpine' },
]
